kind = "web"
previewPath = "/"
title = "MyTestType"
version = "1.0.0"
id = "artifacts/inner-meter"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 24578
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/inner-meter run dev"

[services.env]
PORT = "24578"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/inner-meter", "run", "build"]
publicDir = "artifacts/inner-meter/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
