import type { Character } from "../types";

export const CHARACTERS: Character[] = [
  {
    id: "baby-oracle",
    koreanName: "애기보살",
    englishName: "Baby Oracle",
    subtitle: "Pure & Innocent Divine Spirit",
    emoji: "🌸",
    description: "Friendly, warm and intuitive. She speaks like a cheerful elder sister who genuinely cares about you.",
    speciality: "Love & Relationships",
    colorFrom: "from-pink-500",
    colorTo: "to-rose-400",
    glowColor: "shadow-pink-500/40",
    borderColor: "border-pink-400/40",
    accentColor: "text-pink-300",
  },
  {
    id: "lunar-goddess",
    koreanName: "선녀보살",
    englishName: "Lunar Goddess",
    subtitle: "Elegant & Mysterious Moon Spirit",
    emoji: "🌙",
    description: "Elegant, refined and deeply mystical. She sees the hidden currents beneath the surface of your life.",
    speciality: "Life Path & Destiny",
    colorFrom: "from-violet-600",
    colorTo: "to-indigo-500",
    glowColor: "shadow-violet-500/40",
    borderColor: "border-violet-400/40",
    accentColor: "text-violet-300",
  },
  {
    id: "sky-warrior",
    koreanName: "천신도령",
    englishName: "Sky Warrior",
    subtitle: "Powerful & Confident Heavenly Spirit",
    emoji: "⚡",
    description: "Bold, direct and powerful. He cuts through the noise and tells you exactly what your fate holds.",
    speciality: "Career & Success",
    colorFrom: "from-amber-500",
    colorTo: "to-orange-500",
    glowColor: "shadow-amber-500/40",
    borderColor: "border-amber-400/40",
    accentColor: "text-amber-300",
  },
  {
    id: "grand-shaman",
    koreanName: "무속인",
    englishName: "Grand Shaman",
    subtitle: "Direct & Traditional Karma Seer",
    emoji: "🔮",
    description: "Traditional, no-nonsense and deeply experienced. She reads the karmic threads of your life with unwavering honesty.",
    speciality: "Karma & Past Lives",
    colorFrom: "from-emerald-600",
    colorTo: "to-teal-500",
    glowColor: "shadow-emerald-500/40",
    borderColor: "border-emerald-400/40",
    accentColor: "text-emerald-300",
  },
  {
    id: "sage-master",
    koreanName: "법사",
    englishName: "Sage Master",
    subtitle: "Calm & Philosophical Ancient Soul",
    emoji: "📿",
    description: "Serene, philosophical and deeply wise. He reveals the spiritual patterns that shape your entire existence.",
    speciality: "Wealth & Fortune",
    colorFrom: "from-slate-500",
    colorTo: "to-blue-600",
    glowColor: "shadow-slate-500/40",
    borderColor: "border-slate-400/40",
    accentColor: "text-slate-300",
  },
];
