import type { Character } from "../types";

export const CHARACTERS: Character[] = [
  {
    id: "baby-oracle",
    koreanName: "애기보살",
    englishName: "Baby Oracle",
    emoji: "🌸",
    subtitles: {
      ko: "맑고 순수한 신령",
      en: "Pure & Innocent Divine Spirit",
      ja: "清らかで純粋な神霊",
      es: "Espíritu Divino Puro e Inocente",
      pt: "Espírito Divino Puro e Inocente",
      fr: "Esprit Divin Pur et Innocent",
    },
    descriptions: {
      ko: "다정하고 따뜻한 언니 같은 신령이에요. 솔직하고 친근하게 당신의 마음을 어루만져 드릴게요.",
      en: "Friendly, warm and intuitive. She speaks like a cheerful elder sister who genuinely cares about you.",
      ja: "優しく温かい、姉のような神霊です。率直で親しみやすく、あなたの心に寄り添います。",
      es: "Amigable, cálida e intuitiva. Habla como una alegre hermana mayor que genuinamente se preocupa por ti.",
      pt: "Amigável, calorosa e intuitiva. Ela fala como uma alegre irmã mais velha que genuinamente se importa com você.",
      fr: "Amicale, chaleureuse et intuitive. Elle parle comme une sœur aînée joyeuse qui se soucie vraiment de vous.",
    },
    specialities: {
      ko: "연애 & 인연",
      en: "Love & Relationships",
      ja: "恋愛 & 縁",
      es: "Amor y Relaciones",
      pt: "Amor e Relacionamentos",
      fr: "Amour et Relations",
    },
    colorFrom: "from-pink-500",
    colorTo: "to-rose-400",
    glowColor: "shadow-pink-500/40",
    borderColor: "border-pink-400/40",
    accentColor: "text-pink-300",
  },
  {
    id: "lunar-goddess",
    koreanName: "선녀보살",
    englishName: "Lunar Goddess",
    emoji: "🌙",
    subtitles: {
      ko: "우아하고 신비로운 달의 신령",
      en: "Elegant & Mysterious Moon Spirit",
      ja: "優雅で神秘的な月の神霊",
      es: "Espíritu de Luna Elegante y Misterioso",
      pt: "Espírito da Lua Elegante e Misterioso",
      fr: "Esprit de Lune Élégant et Mystérieux",
    },
    descriptions: {
      ko: "우아하고 고고한 신령이에요. 삶의 깊은 흐름과 숨겨진 진실을 꿰뚫어 보는 눈을 가지고 있어요.",
      en: "Elegant, refined and deeply mystical. She sees the hidden currents beneath the surface of your life.",
      ja: "優雅で洗練された、深く神秘的な神霊です。あなたの人生の表面下に隠れた流れを見通します。",
      es: "Elegante, refinada y profundamente mística. Ella ve las corrientes ocultas bajo la superficie de tu vida.",
      pt: "Elegante, refinada e profundamente mística. Ela vê as correntes ocultas sob a superfície da sua vida.",
      fr: "Élégante, raffinée et profondément mystique. Elle voit les courants cachés sous la surface de votre vie.",
    },
    specialities: {
      ko: "인생 길 & 운명",
      en: "Life Path & Destiny",
      ja: "人生の道 & 運命",
      es: "Camino de Vida y Destino",
      pt: "Caminho de Vida e Destino",
      fr: "Chemin de Vie et Destin",
    },
    colorFrom: "from-violet-600",
    colorTo: "to-indigo-500",
    glowColor: "shadow-violet-500/40",
    borderColor: "border-violet-400/40",
    accentColor: "text-violet-300",
  },
  {
    id: "sky-warrior",
    koreanName: "천신도령",
    englishName: "Sky Warrior",
    emoji: "⚡",
    subtitles: {
      ko: "강하고 당당한 하늘의 신령",
      en: "Powerful & Confident Heavenly Spirit",
      ja: "力強く堂々とした天の神霊",
      es: "Espíritu Celestial Poderoso y Confiado",
      pt: "Espírito Celestial Poderoso e Confiante",
      fr: "Esprit Céleste Puissant et Confiant",
    },
    descriptions: {
      ko: "대담하고 직설적인 신령이에요. 복잡한 말 없이 당신의 운명을 정확하게 꿰뚫어 말해드려요.",
      en: "Bold, direct and powerful. He cuts through the noise and tells you exactly what your fate holds.",
      ja: "大胆で直接的、力強い神霊です。無駄なく、あなたの運命を正確に見通して伝えます。",
      es: "Audaz, directo y poderoso. Corta el ruido y te dice exactamente lo que depara tu destino.",
      pt: "Ousado, direto e poderoso. Ele corta o ruído e te diz exatamente o que o seu destino reserva.",
      fr: "Audacieux, direct et puissant. Il coupe à travers le bruit et vous dit exactement ce que votre destin réserve.",
    },
    specialities: {
      ko: "직업 & 성공",
      en: "Career & Success",
      ja: "仕事 & 成功",
      es: "Carrera y Éxito",
      pt: "Carreira e Sucesso",
      fr: "Carrière et Succès",
    },
    colorFrom: "from-amber-500",
    colorTo: "to-orange-500",
    glowColor: "shadow-amber-500/40",
    borderColor: "border-amber-400/40",
    accentColor: "text-amber-300",
  },
  {
    id: "grand-shaman",
    koreanName: "무속인",
    englishName: "Grand Shaman",
    emoji: "🔮",
    subtitles: {
      ko: "직설적인 전통 무속인",
      en: "Direct & Traditional Karma Seer",
      ja: "直接的で伝統的なカルマの見者",
      es: "Vidente de Karma Directa y Tradicional",
      pt: "Vidente de Karma Direta e Tradicional",
      fr: "Voyante de Karma Directe et Traditionnelle",
    },
    descriptions: {
      ko: "전통 무속의 기운으로 당신의 카르마와 전생의 인연을 솔직하게 풀어드려요.",
      en: "Traditional, no-nonsense and deeply experienced. She reads the karmic threads of your life with unwavering honesty.",
      ja: "伝統的で率直、深い経験を持つ神霊です。あなたの人生のカルマの糸を揺るぎない誠実さで読み解きます。",
      es: "Tradicional, directa y profundamente experimentada. Ella lee los hilos kármicos de tu vida con honestidad inquebrantable.",
      pt: "Tradicional, direta e profundamente experiente. Ela lê os fios kármicos da sua vida com honestidade inabalável.",
      fr: "Traditionnelle, sans détour et profondément expérimentée. Elle lit les fils karmiques de votre vie avec une honnêteté inébranlable.",
    },
    specialities: {
      ko: "카르마 & 전생",
      en: "Karma & Past Lives",
      ja: "カルマ & 前世",
      es: "Karma y Vidas Pasadas",
      pt: "Karma e Vidas Passadas",
      fr: "Karma et Vies Passées",
    },
    colorFrom: "from-emerald-600",
    colorTo: "to-teal-500",
    glowColor: "shadow-emerald-500/40",
    borderColor: "border-emerald-400/40",
    accentColor: "text-emerald-300",
  },
  {
    id: "sage-master",
    koreanName: "법사",
    englishName: "Sage Master",
    emoji: "📿",
    subtitles: {
      ko: "고요하고 깊은 지혜의 신령",
      en: "Calm & Philosophical Ancient Soul",
      ja: "穏やかで哲学的な古代の魂",
      es: "Alma Antigua Tranquila y Filosófica",
      pt: "Alma Antiga Calma e Filosófica",
      fr: "Âme Ancienne Calme et Philosophique",
    },
    descriptions: {
      ko: "고요하고 깊은 법사님이에요. 당신의 삶 전체에 흐르는 영적인 패턴을 밝혀드려요.",
      en: "Serene, philosophical and deeply wise. He reveals the spiritual patterns that shape your entire existence.",
      ja: "穏やかで哲学的、深い知恵を持つ法師です。あなたの存在全体を形作る霊的なパターンを明かします。",
      es: "Sereno, filosófico y profundamente sabio. Él revela los patrones espirituales que dan forma a toda tu existencia.",
      pt: "Sereno, filosófico e profundamente sábio. Ele revela os padrões espirituais que moldam toda a sua existência.",
      fr: "Serein, philosophique et profondément sage. Il révèle les schémas spirituels qui façonnent toute votre existence.",
    },
    specialities: {
      ko: "재물운 & 행운",
      en: "Wealth & Fortune",
      ja: "財運 & 幸運",
      es: "Riqueza y Fortuna",
      pt: "Riqueza e Fortuna",
      fr: "Richesse et Fortune",
    },
    colorFrom: "from-slate-500",
    colorTo: "to-blue-600",
    glowColor: "shadow-slate-500/40",
    borderColor: "border-slate-400/40",
    accentColor: "text-slate-300",
  },
];
