import type { Product } from "../types";

export const PRODUCTS: Product[] = [
  {
    id: "basic-reading",
    name: "Quick Reading",
    nameKo: "빠른 점사",
    description: "A focused 3-question reading on the topic of your choice.",
    price: 9900,
    currency: "KRW",
    icon: "🃏",
    features: [
      "3 questions answered",
      "Your current energy flow",
      "Immediate guidance",
    ],
  },
  {
    id: "love-reading",
    name: "Love & Relationships",
    nameKo: "연애 & 인연",
    description: "Deep dive into your love life, compatibility, and romantic destiny.",
    price: 14900,
    currency: "KRW",
    icon: "💕",
    popular: false,
    features: [
      "Love energy analysis",
      "Soulmate timing",
      "Relationship karma",
      "5 questions answered",
    ],
  },
  {
    id: "career-reading",
    name: "Career & Wealth",
    nameKo: "직업 & 재물운",
    description: "Unlock your wealth potential and career destiny.",
    price: 14900,
    currency: "KRW",
    icon: "💼",
    features: [
      "Career path clarity",
      "Wealth timing window",
      "Business compatibility",
      "5 questions answered",
    ],
  },
  {
    id: "full-reading",
    name: "Full Life Reading",
    nameKo: "종합 인생 점사",
    description: "Complete life destiny analysis — past, present, and future revealed.",
    price: 19900,
    currency: "KRW",
    icon: "🌟",
    badge: "Most Popular",
    popular: true,
    features: [
      "Full destiny mapping",
      "Life turning points",
      "Love, career & wealth",
      "10 questions answered",
      "PDF report included",
    ],
  },
  {
    id: "ask-anything",
    name: "Ask Anything",
    nameKo: "무엇이든 물어보세요",
    description: "Unlimited live chat session with your chosen spiritual guide.",
    price: 24900,
    currency: "KRW",
    icon: "💬",
    badge: "Premium",
    features: [
      "Unlimited questions",
      "Real-time chat session",
      "30-minute session",
      "Voice message option",
      "Session transcript",
    ],
  },
];
