import type { Product } from "../types";

export const PRODUCTS: Product[] = [
  {
    id: "daily-fortune",
    name: "Daily Fortune",
    nameKo: "오늘의 운세",
    free: true,
    icon: "🌅",
    descriptions: {
      ko: "오늘 하루의 운기를 무료로 확인해보세요.",
      en: "Check your energy and fortune for today — completely free.",
      ja: "今日の運気を無料で確認しましょう。",
      es: "Consulta tu energía y fortuna de hoy — completamente gratis.",
      pt: "Verifique sua energia e fortuna de hoje — completamente grátis.",
      fr: "Consultez votre énergie et votre fortune pour aujourd'hui — entièrement gratuit.",
    },
    features: {
      ko: ["오늘의 기운 분석", "한 줄 메세지", "행운의 색상 & 숫자"],
      en: ["Today's energy reading", "One-line message", "Lucky color & number"],
      ja: ["今日のエネルギー分析", "一言メッセージ", "ラッキーカラー & ナンバー"],
      es: ["Lectura de energía de hoy", "Mensaje en una línea", "Color y número de la suerte"],
      pt: ["Leitura de energia de hoje", "Mensagem em uma linha", "Cor e número da sorte"],
      fr: ["Lecture d'énergie d'aujourd'hui", "Message en une ligne", "Couleur et chiffre porte-bonheur"],
    },
  },
  {
    id: "quick-reading",
    name: "Quick Reading",
    nameKo: "빠른 점사",
    icon: "🃏",
    descriptions: {
      ko: "지금 궁금한 것을 바로 물어보세요.",
      en: "Ask what's on your mind right now.",
      ja: "今気になることをすぐに聞いてください。",
      es: "Pregunta lo que tienes en mente ahora mismo.",
      pt: "Pergunte o que está em sua mente agora.",
      fr: "Demandez ce qui vous préoccupe maintenant.",
    },
    features: {
      ko: ["질문 3개 답변", "현재 기운 분석", "즉각적인 조언"],
      en: ["3 questions answered", "Current energy reading", "Immediate guidance"],
      ja: ["3つの質問に回答", "現在のエネルギー分析", "即座のアドバイス"],
      es: ["3 preguntas respondidas", "Lectura de energía actual", "Orientación inmediata"],
      pt: ["3 perguntas respondidas", "Leitura de energia atual", "Orientação imediata"],
      fr: ["3 questions répondues", "Lecture d'énergie actuelle", "Guidance immédiate"],
    },
  },
  {
    id: "love-reading",
    name: "Love & Relationships",
    nameKo: "연애 & 인연",
    icon: "💕",
    descriptions: {
      ko: "사랑과 인연의 흐름을 살펴드려요.",
      en: "Explore your love life and romantic destiny.",
      ja: "恋愛と縁の流れを見てもらいましょう。",
      es: "Explora tu vida amorosa y tu destino romántico.",
      pt: "Explore sua vida amorosa e destino romântico.",
      fr: "Explorez votre vie amoureuse et votre destin romantique.",
    },
    features: {
      ko: ["연애 기운 분석", "인연의 타이밍", "관계 카르마", "질문 5개 답변"],
      en: ["Love energy analysis", "Soulmate timing", "Relationship karma", "5 questions answered"],
      ja: ["恋愛エネルギー分析", "縁のタイミング", "関係のカルマ", "5つの質問に回答"],
      es: ["Análisis de energía amorosa", "Timing del alma gemela", "Karma de relación", "5 preguntas respondidas"],
      pt: ["Análise de energia amorosa", "Timing da alma gêmea", "Karma de relacionamento", "5 perguntas respondidas"],
      fr: ["Analyse d'énergie amoureuse", "Timing de l'âme sœur", "Karma de relation", "5 questions répondues"],
    },
  },
  {
    id: "career-reading",
    name: "Career & Wealth",
    nameKo: "직업 & 재물운",
    icon: "💼",
    descriptions: {
      ko: "직업운과 재물운을 함께 살펴드려요.",
      en: "Unlock your wealth potential and career path.",
      ja: "仕事運と財運を一緒に見てもらいましょう。",
      es: "Descubre tu potencial de riqueza y camino profesional.",
      pt: "Descubra seu potencial de riqueza e caminho profissional.",
      fr: "Découvrez votre potentiel de richesse et votre parcours professionnel.",
    },
    features: {
      ko: ["직업 방향 분석", "재물운 타이밍", "사업 궁합", "질문 5개 답변"],
      en: ["Career path clarity", "Wealth timing window", "Business compatibility", "5 questions answered"],
      ja: ["仕事の方向分析", "財運タイミング", "ビジネス相性", "5つの質問に回答"],
      es: ["Claridad del camino profesional", "Ventana de timing de riqueza", "Compatibilidad empresarial", "5 preguntas respondidas"],
      pt: ["Clareza do caminho profissional", "Janela de timing de riqueza", "Compatibilidade empresarial", "5 perguntas respondidas"],
      fr: ["Clarté du chemin professionnel", "Fenêtre de timing de richesse", "Compatibilité professionnelle", "5 questions répondues"],
    },
  },
  {
    id: "full-reading",
    name: "Full Life Reading",
    nameKo: "종합 인생 점사",
    icon: "🌟",
    descriptions: {
      ko: "과거·현재·미래를 종합적으로 풀어드려요.",
      en: "Full destiny analysis — past, present, and future.",
      ja: "過去・現在・未来を総合的に見てもらいましょう。",
      es: "Análisis completo de destino — pasado, presente y futuro.",
      pt: "Análise completa do destino — passado, presente e futuro.",
      fr: "Analyse complète du destin — passé, présent et futur.",
    },
    features: {
      ko: ["전체 운명 분석", "인생 전환점", "연애·직업·재물 통합", "질문 10개 답변"],
      en: ["Full destiny mapping", "Life turning points", "Love, career & wealth", "10 questions answered"],
      ja: ["全体的な運命分析", "人生の転換点", "恋愛・仕事・財運統合", "10の質問に回答"],
      es: ["Mapeo completo del destino", "Puntos de inflexión", "Amor, carrera y riqueza", "10 preguntas respondidas"],
      pt: ["Mapeamento completo do destino", "Pontos de virada", "Amor, carreira e riqueza", "10 perguntas respondidas"],
      fr: ["Cartographie complète du destin", "Points tournants de vie", "Amour, carrière et richesse", "10 questions répondues"],
    },
  },
  {
    id: "ask-anything",
    name: "Ask Anything",
    nameKo: "무엇이든 물어보세요",
    icon: "💬",
    descriptions: {
      ko: "신령과 실시간으로 무엇이든 나눠보세요.",
      en: "Live chat session with your spirit guide.",
      ja: "神霊とリアルタイムで何でも話し合いましょう。",
      es: "Sesión de chat en vivo con tu guía espiritual.",
      pt: "Sessão de chat ao vivo com seu guia espiritual.",
      fr: "Session de chat en direct avec votre guide spirituel.",
    },
    features: {
      ko: ["무제한 질문", "실시간 채팅 세션", "30분 세션"],
      en: ["Unlimited questions", "Real-time chat", "30-minute session"],
      ja: ["無制限の質問", "リアルタイムチャット", "30分セッション"],
      es: ["Preguntas ilimitadas", "Chat en tiempo real", "Sesión de 30 minutos"],
      pt: ["Perguntas ilimitadas", "Chat em tempo real", "Sessão de 30 minutos"],
      fr: ["Questions illimitées", "Chat en temps réel", "Session de 30 minutes"],
    },
  },
];
